const express=require('express');
const otherRoutes=express.Router();
const {createSubject,addHomework,fetchAllSubjectsByGrade,fetchAllSubject}=require("../__controllers/subjectCreation");
const {creatingExam,addingMarks,dispalyAllExamByClass}=require("../__controllers/exams");
const { markAttendance,getAllAttendaceByClass, getAttendanceByDate}=require("../__controllers/attendance");
const {getAllStudents}=require("../__controllers/class");
const { getHomeworkByDateAndGrade, createHomework ,addReviewToStudent,fetchHomeWorkReview} = require('../__controllers/homework');
const {  getExamsByGrade, getSubjectsByExamName } = require('../__controllers/marks');

otherRoutes.post("/create-subject",createSubject);
otherRoutes.get("/getallsubject",fetchAllSubject);
otherRoutes.post("/add-homework",addHomework);
otherRoutes.post("/creating-exam",creatingExam);
otherRoutes.post("/adding-marks",addingMarks);
// otherRoutes.post("/create-attendance",createAttendance);
otherRoutes.post("/mark-attendance",markAttendance);
otherRoutes.post("/getAllClassStudents",getAllStudents);
otherRoutes.post("/get-all-attendance-by-class",getAllAttendaceByClass);
otherRoutes.post("/homework",getHomeworkByDateAndGrade);
otherRoutes.post("/createHomework",createHomework);
// otherRoutes.post("/getMarks",getStudentMarksAndAverage);
// otherRoutes.post("/mark-attendance",markAttendance);
// otherRoutes.post("/getAllClassStudents",getAllStudents);
// otherRoutes.post("/get-all-attendance-by-class",getAllAttendaceByClass);
otherRoutes.post("/get-exam-by-grade",dispalyAllExamByClass);
otherRoutes.post("/get-subject-by-grade",fetchAllSubjectsByGrade);
otherRoutes.post("/getattendancebydate",getAttendanceByDate);
// otherRoutes.post("/getexamnames",getExamsByGrade);
// otherRoutes.post("/getexamnames/getexamsubject",getSubjectsByExamName);
otherRoutes.post("/review-homework",addReviewToStudent);
otherRoutes.post("/get-homework-review",fetchHomeWorkReview);
module.exports=otherRoutes;